services:
    cloudsandwich.menufiller.files:
        class: CloudSandwich\FileBundle\Menu\MenuFiller
        arguments: [@translator]
        tags:
            - { name: cloudsandwich.menufiller }

    cloudsandwich.filemanager:
        class: CloudSandwich\FileBundle\Manager\FileManager
        arguments: ["@translator","@security.context"]

    cloudsandwich.openers.default:
        class: CloudSandwich\FileBundle\Opener\DefaultOpener
        tags:
            - { name: cloudsandwich.fileopener}

    cloudsandwich.openers.image:
        class: CloudSandwich\FileBundle\Opener\ImageOpener
        tags:
            - { name: cloudsandwich.fileopener}

    cloudsandwich.openers.text:
        class: CloudSandwich\FileBundle\Opener\TextOpener
        tags:
            - { name: cloudsandwich.fileopener}
    cloudsandwich.openers.pdf:
        class: CloudSandwich\FileBundle\Opener\PdfOpener
        tags:
            - { name: cloudsandwich.fileopener}
